name: Workflow demo
on: [push]
jobs:
  run-java:
    runs-on: ubuntu-latest
    steps:
      - name: checkout action repository
        uses: actions/checkout@v2
        with: 
          repository: ex1642/actions
          #token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: main
          path: ./.github/actions/actions
      - name: Test using action
        uses: ./.github/actions/actions/java-build-base